<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Application\Action\HomeAction::class => App\Application\Action\HomeActionFactory::class,
            App\Application\Action\ListaPaises::class => App\Application\Action\ListaPaisesFactory::class,
            App\Application\Action\PaisesCsv::class => App\Application\Action\PaisesCsvFactory::class,
            App\Application\Action\PaisesExcel::class => App\Application\Action\PaisesExcelFactory::class,
            App\Application\I18n\LocaleMiddleware::class => App\Application\I18n\LocaleMiddlewareFactory::class,
        ],
    ],
];
